import type { Address, Hash } from "viem";
import deployment from "./hsk-testnet.json";

/** Generated by contracts:sync:addresses. Missing deployments disable writes. */
export const testnetDeployment: {
  chainId: 133;
  factory: Address | undefined;
  demoToken: Address | undefined;
  eligibilityProvider: Address | undefined;
  deployer: Address | undefined;
  transactionHashes: Readonly<Record<string, Hash>>;
} = {
  chainId: 133,
  factory: (deployment.factory ?? undefined) as Address | undefined,
  demoToken: (deployment.demoToken ?? undefined) as Address | undefined,
  eligibilityProvider: (deployment.eligibilityProvider ?? undefined) as
    Address | undefined,
  deployer: (deployment.deployer ?? undefined) as Address | undefined,
  transactionHashes: deployment.transactionHashes as Record<string, Hash>,
};
