export const SPONSORED_CLAIM_SIGNING_WINDOW_SECONDS = 5 * 60;
export const SPONSORED_CLAIM_MAX_WINDOW_SECONDS = 15 * 60;
export const MAX_ORGANIZATION_SPONSORED_ACTIONS = 10_000;
export const MAX_SPONSORED_ACTIONS_PER_WALLET_PER_DAY = 100;
export const MAX_SPONSORSHIP_VAULTS = 100;
